### PR TITLE
Clarify install instructions and add badges

### PR DESCRIPTION
**Pull request by Eeems**
Clarified the installation instructions to make it easier for users to understand.

Added badges as recommended by https://remarkable.guide/devel/github.html

### CODE REVIEW

**Comment by Eeems** [comment]
@alex0809 poke

**Comment by Eeems** [comment]
@alex0809 poke again?

**Comment by alex0809** [comment]
Thanks! I didn't monitor my Github for a long while.

I tried to get this repo back into a working state with my latest commit.

However, I don't own a reMarkable device anymore, so I have no way to test changes anymore. At least the latest version can successfully build the binary again :)

**Comment by Eeems** [comment]
> Thanks! I didn't monitor my Github for a long while.
> 
> I tried to get this repo back into a working state with my latest commit.
> 
> However, I don't own a reMarkable device anymore, so I have no way to test changes anymore. At least the latest version can successfully build the binary again :)

https://github.com/timower/rM-docker is something you may find interesting

**Pull request merged**
